"""init

Revision ID: db3d63411e4a
Revises: 
Create Date: 2026-04-13 21:48:16.084895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3d63411e4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_is_archived'), 'projects', ['is_archived'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('fragments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fragments_id'), 'fragments', ['id'], unique=False)
    op.create_index(op.f('ix_fragments_project_id'), 'fragments', ['project_id'], unique=False)
    op.create_index(op.f('ix_fragments_source_type'), 'fragments', ['source_type'], unique=False)
    op.create_index(op.f('ix_fragments_status'), 'fragments', ['status'], unique=False)
    op.create_table('fragment_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fragment_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('fact_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fragment_facts_category'), 'fragment_facts', ['category'], unique=False)
    op.create_index(op.f('ix_fragment_facts_fragment_id'), 'fragment_facts', ['fragment_id'], unique=False)
    op.create_index(op.f('ix_fragment_facts_id'), 'fragment_facts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fragment_facts_id'), table_name='fragment_facts')
    op.drop_index(op.f('ix_fragment_facts_fragment_id'), table_name='fragment_facts')
    op.drop_index(op.f('ix_fragment_facts_category'), table_name='fragment_facts')
    op.drop_table('fragment_facts')
    op.drop_index(op.f('ix_fragments_status'), table_name='fragments')
    op.drop_index(op.f('ix_fragments_source_type'), table_name='fragments')
    op.drop_index(op.f('ix_fragments_project_id'), table_name='fragments')
    op.drop_index(op.f('ix_fragments_id'), table_name='fragments')
    op.drop_table('fragments')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_archived'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
